[package]
name = "time_series_forecasting_for_power_plant_emissions_lstm_xgboost_and_sarima_rs"
description = "Python bindings (PyO3) for time_series_forecasting_for_power_plant_emissions_lstm_xgboost_and_sarima_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "time_series_forecasting_for_power_plant_emissions_lstm_xgboost_and_sarima_rs"
crate-type = ["cdylib"]

[dependencies]
time_series_forecasting_for_power_plant_emissions_lstm_xgboost_and_sarima_core = { path = "../core" }
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
